import type { ArenaConfig } from "./types";

// One themed arena per element, procedurally built by components/game/Arena.tsx
// from these params (SRD 3.2 Environment Reactivity System / PRD 6.3).
export const ARENAS: Record<string, ArenaConfig> = {
  fire: {
    id: "fire",
    name: "The Furnace Caldera",
    element: "fire",
    era: "primordial",
    skyTop: "#1a0806",
    skyBottom: "#ff5a1f",
    fogColor: "#3a1206",
    fogDensity: 0.035,
    floorColor: "#4f2d20",
    floorEmissive: "#ff5a1f",
    rimLight: "#ff8a3d",
    ambientTrack: "fire",
    particle: "embers",
    layout: "scattered",
    description: "A collapsed volcanic ring where the rock never fully cooled.",
  },
  ice: {
    id: "ice",
    name: "The Hollow Glacier",
    element: "ice",
    era: "primordial",
    skyTop: "#050a12",
    skyBottom: "#3fa9c9",
    fogColor: "#0c1c26",
    fogDensity: 0.03,
    floorColor: "#2a4f64",
    floorEmissive: "#7fe3ff",
    rimLight: "#9fe9ff",
    ambientTrack: "ice",
    particle: "snow",
    layout: "ring",
    description: "A cavern of packed frost so old it rings like glass.",
  },
  storm_zen: {
    id: "storm_zen",
    name: "The Still Peak",
    element: "electric",
    era: "ancient",
    skyTop: "#0a0714",
    skyBottom: "#4b3a86",
    fogColor: "#160f2a",
    fogDensity: 0.025,
    floorColor: "#392d58",
    floorEmissive: "#b98bff",
    rimLight: "#c9a8ff",
    ambientTrack: "storm_zen",
    particle: "motes",
    layout: "floating",
    description: "A mountain temple where the air stays charged even in stillness.",
  },
  concrete_arena: {
    id: "concrete_arena",
    name: "The Underground",
    element: "kinetic",
    era: "futuristic",
    skyTop: "#0a0a0a",
    skyBottom: "#3a2f22",
    fogColor: "#1a1712",
    fogDensity: 0.04,
    floorColor: "#48423b",
    floorEmissive: "#ffb454",
    rimLight: "#ffb454",
    ambientTrack: "concrete_arena",
    particle: "dust",
    layout: "rows",
    description: "A stripped parking structure turned fight pit, chalk dust in the lights.",
  },
  neon_alley: {
    id: "neon_alley",
    name: "Neon Alley",
    element: "speed",
    era: "futuristic",
    skyTop: "#0a0416",
    skyBottom: "#ff4fd8",
    fogColor: "#180a2a",
    fogDensity: 0.045,
    floorColor: "#34234f",
    floorEmissive: "#ff4fd8",
    rimLight: "#7ef0ff",
    ambientTrack: "neon_alley",
    particle: "sparks",
    layout: "rows",
    description: "A rain-slick backstreet lit only by signage that never turns off.",
  },
  stone_quarry: {
    id: "stone_quarry",
    name: "The Quarry",
    element: "earth",
    era: "ancient",
    skyTop: "#100d08",
    skyBottom: "#6b5636",
    fogColor: "#241d12",
    fogDensity: 0.035,
    floorColor: "#5d4f37",
    floorEmissive: "#b5ff6a",
    rimLight: "#c9ff8a",
    ambientTrack: "stone_quarry",
    particle: "dust",
    layout: "scattered",
    description: "A terraced rock cut, still settling, moss growing in the fault lines.",
  },
  server_core: {
    id: "server_core",
    name: "The Core",
    element: "tech",
    era: "futuristic",
    skyTop: "#020608",
    skyBottom: "#0f3a44",
    fogColor: "#03181c",
    fogDensity: 0.03,
    floorColor: "#193942",
    floorEmissive: "#43f5ff",
    rimLight: "#43f5ff",
    ambientTrack: "server_core",
    particle: "motes",
    layout: "rows",
    description: "A server hall repurposed as a ring; the cooling fans never stop.",
  },
  mirror_hall: {
    id: "mirror_hall",
    name: "The Hall of Mirrors",
    element: "shift",
    era: "medieval",
    skyTop: "#0c0c12",
    skyBottom: "#4a4a5e",
    fogColor: "#181820",
    fogDensity: 0.03,
    floorColor: "#424253",
    floorEmissive: "#d9d9e8",
    rimLight: "#e6e6f5",
    ambientTrack: "mirror_hall",
    particle: "motes",
    layout: "ring",
    description: "A hall of warped glass that shows you back wrong, on purpose.",
  },
  dojo: {
    id: "dojo",
    name: "The Dojo",
    element: "steel",
    era: "medieval",
    skyTop: "#08080a",
    skyBottom: "#8a8a9a",
    fogColor: "#141418",
    fogDensity: 0.02,
    floorColor: "#3b342c",
    floorEmissive: "#e6e6f0",
    rimLight: "#e6e6f0",
    ambientTrack: "dojo",
    particle: "petals",
    layout: "rows",
    description: "A bare wooden hall, one blade's length wide, kept in perfect order.",
  },
  sky_temple: {
    id: "sky_temple",
    name: "Sky Temple",
    element: "wind",
    era: "ancient",
    skyTop: "#061018",
    skyBottom: "#7fe3c9",
    fogColor: "#0c2420",
    fogDensity: 0.02,
    floorColor: "#2d4f48",
    floorEmissive: "#baffe0",
    rimLight: "#baffe0",
    ambientTrack: "sky_temple",
    particle: "leaves",
    layout: "floating",
    description: "A ring of floating stone above the clouds, no railings anywhere.",
  },
  storm_ring: {
    id: "storm_ring",
    name: "Storm Ring",
    element: "lightning",
    era: "medieval",
    skyTop: "#0a0a10",
    skyBottom: "#4a4a1e",
    fogColor: "#1a1a10",
    fogDensity: 0.04,
    floorColor: "#42422d",
    floorEmissive: "#f5e642",
    rimLight: "#f5e642",
    ambientTrack: "storm_ring",
    particle: "sparks",
    layout: "ring",
    description: "An open-air stadium under a storm that never actually lands.",
  },
  void_throne: {
    id: "void_throne",
    name: "The Void Throne",
    element: "void",
    era: "futuristic",
    skyTop: "#000000",
    skyBottom: "#1a0f2e",
    fogColor: "#0a0614",
    fogDensity: 0.05,
    floorColor: "#231e34",
    floorEmissive: "#b98bff",
    rimLight: "#ffd24a",
    ambientTrack: "void_throne",
    particle: "ash",
    layout: "floating",
    description: "The room at the center of the Mogsphere. Viraat built it first.",
  },
};

export const ARENA_LIST = Object.values(ARENAS);
