import type { CharacterConfig } from "./types";

// The full Mog Off roster (PRD 6.2 / SRD sec 5). Stats, moves, and visual
// params are data-driven so the shared combat resolver, character rig
// builder, and arena builder work for all twelve without new code paths.
// Combat is hand-to-hand only (no weapon inventory) — per-character feel
// comes from `build` (see BUILD_POWER in lib/combat.ts) plus the special.
export const CHARACTERS: Record<string, CharacterConfig> = {
  gautham: {
    id: "gautham",
    name: "Gautham",
    title: "The Furnace",
    element: "fire",
    bio: "Thinks he's the main character. In the Mogsphere, he might actually be right.",
    health: 1000,
    build: "normal",
    modelKey: "vanguard",
    accessory: "spikes",
    arenaId: "fire",
    voiceLine: "Burn with me!",
    introLines: ["Burn with me!", "You picked the wrong ring.", "Watch closely — this is the good part."],
    colors: { primary: "#3a160c", secondary: "#d1401f", emissive: "#ff7a1a" },
    moves: {
      special: { damage: 220, animation: "gautham_special_chainpull", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: true,
  },
  garv: {
    id: "garv",
    name: "Garv",
    title: "The Stillwater",
    element: "ice",
    bio: "Would rather win with one perfect cut than ten sloppy ones.",
    health: 1000,
    build: "normal",
    modelKey: "ely",
    accessory: "crystal",
    arenaId: "ice",
    voiceLine: "Everything ends in silence.",
    introLines: ["Everything ends in silence.", "Make it quick, then.", "You'll feel this later. Just not for long."],
    colors: { primary: "#0e2430", secondary: "#1c3a52", emissive: "#7fe3ff" },
    moves: {
      special: { damage: 220, animation: "garv_special_deepfreeze", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: true,
  },
  anvith: {
    id: "anvith",
    name: "Anvith",
    title: "The Current",
    element: "electric",
    bio: "Meditates between rounds. It works better than it should.",
    health: 1000,
    build: "normal",
    modelKey: "ely",
    accessory: "beads",
    arenaId: "storm_zen",
    voiceLine: "Feel the current.",
    introLines: ["Feel the current.", "Breathe. This won't take long.", "I already saw how this ends."],
    colors: { primary: "#171029", secondary: "#2b2140", emissive: "#b98bff" },
    moves: {
      special: { damage: 200, animation: "anvith_special_conduit", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ryan: {
    id: "ryan",
    name: "Ryan",
    title: "The Underground",
    element: "kinetic",
    bio: "Doesn't need an element. Just needs one good angle to close the distance.",
    health: 1150,
    build: "bulky",
    modelKey: "ely",
    accessory: "none",
    arenaId: "concrete_arena",
    voiceLine: "Down you go!",
    introLines: ["Down you go!", "Let's skip the small talk.", "I've done this a hundred times."],
    colors: { primary: "#201c18", secondary: "#4a3226", emissive: "#ffb454" },
    moves: {
      special: { damage: 230, animation: "ryan_special_suplex", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  chandan: {
    id: "chandan",
    name: "Chandan",
    title: "The Afterimage",
    element: "speed",
    bio: "Talks the whole fight. You only notice when the talking stops.",
    health: 850,
    build: "slim",
    modelKey: "ely",
    accessory: "hood",
    arenaId: "neon_alley",
    voiceLine: "Catch me if you can.",
    introLines: ["Catch me if you can.", "Oh, you're actually trying? Cute.", "Blink and it's over."],
    colors: { primary: "#140a24", secondary: "#241f38", emissive: "#ff4fd8" },
    moves: {
      special: { damage: 200, animation: "chandan_special_afterimage", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  elango: {
    id: "elango",
    name: "Elango",
    title: "The Quarry",
    element: "earth",
    bio: "Slow to anger. The ground gets there first.",
    health: 1300,
    build: "tank",
    modelKey: "ely",
    accessory: "pauldron",
    arenaId: "stone_quarry",
    voiceLine: "The ground remembers.",
    introLines: ["The ground remembers.", "I've been patient long enough.", "Sit down. This won't take long."],
    colors: { primary: "#2c2416", secondary: "#55442c", emissive: "#b5ff6a" },
    moves: {
      special: { damage: 240, animation: "elango_special_upheaval", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  dev: {
    id: "dev",
    name: "Dev",
    title: "The Core",
    element: "tech",
    bio: "Brought receipts, a drone, and three backup plans.",
    health: 1000,
    build: "normal",
    modelKey: "ely",
    accessory: "visor",
    arenaId: "server_core",
    voiceLine: "Running final sequence.",
    introLines: ["Running final sequence.", "I already simulated this. I win.", "Don't take it personally."],
    colors: { primary: "#04171c", secondary: "#1b1f2a", emissive: "#43f5ff" },
    moves: {
      special: { damage: 210, animation: "dev_special_overclock", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  aadit: {
    id: "aadit",
    name: "Aadit",
    title: "The Mirror",
    element: "shift",
    bio: "Already fought this exact fight in his head. He won that one too.",
    health: 1000,
    build: "normal",
    modelKey: "ely",
    accessory: "chrome",
    arenaId: "mirror_hall",
    voiceLine: "I've already won this fight.",
    introLines: ["I've already won this fight.", "You'll fight exactly like I expect.", "I'm going to enjoy copying that."],
    colors: { primary: "#1c1c26", secondary: "#2e2e38", emissive: "#d9d9e8" },
    moves: {
      special: { damage: 215, animation: "aadit_special_copycat", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  rishi: {
    id: "rishi",
    name: "Rishi",
    title: "The Silence",
    element: "steel",
    bio: "Says almost nothing. The blade says the rest.",
    health: 850,
    build: "slim",
    modelKey: "ely",
    accessory: "topknot",
    arenaId: "dojo",
    voiceLine: "One cut is enough.",
    introLines: ["One cut is enough.", "...", "Draw your weapon. I'll wait."],
    colors: { primary: "#18140f", secondary: "#1a1a22", emissive: "#e6e6f0" },
    moves: {
      special: { damage: 260, animation: "rishi_special_iaido", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ronith: {
    id: "ronith",
    name: "Ronith",
    title: "The Gale",
    element: "wind",
    bio: "Never lands where you're looking.",
    health: 850,
    build: "slim",
    modelKey: "ely",
    accessory: "scarf",
    arenaId: "sky_temple",
    voiceLine: "Try to keep up.",
    introLines: ["Try to keep up.", "You'll need to be faster than that.", "Let's see if you can even touch me."],
    colors: { primary: "#102420", secondary: "#1e3a34", emissive: "#baffe0" },
    moves: {
      special: { damage: 205, animation: "ronith_special_cyclone", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  tej: {
    id: "tej",
    name: "Tej",
    title: "The Strike",
    element: "lightning",
    bio: "Too fast to block, too impatient to combo.",
    health: 1000,
    build: "normal",
    modelKey: "ely",
    accessory: "shins",
    arenaId: "storm_ring",
    voiceLine: "Too fast, too late.",
    introLines: ["Too fast, too late.", "I'm already bored.", "Try to keep this interesting."],
    colors: { primary: "#1c1c10", secondary: "#2a2340", emissive: "#f5e642" },
    moves: {
      special: { damage: 215, animation: "tej_special_thunderstep", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  viraat: {
    id: "viraat",
    name: "Viraat",
    title: "The Architect",
    element: "void",
    bio: "Built the arena. Decides who leaves it.",
    health: 1300,
    build: "tank",
    modelKey: "ely",
    accessory: "crown",
    arenaId: "void_throne",
    voiceLine: "I built this arena. I decide who leaves it.",
    introLines: ["I built this arena. I decide who leaves it.", "Everyone ends up here eventually.", "Let's see what you've learned."],
    colors: { primary: "#0a0714", secondary: "#0a0a0f", emissive: "#b98bff" },
    moves: {
      special: { damage: 280, animation: "viraat_special_keystone", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
    isStoryBoss: true,
  },
  overmog: {
    id: "overmog",
    name: "Overmog",
    title: "The Unranked",
    element: "prism",
    bio: "Not a thirteenth fighter. What's left in the ring after twelve people spend years trying to out-mog each other in it.",
    health: 1600,
    build: "tank",
    accessory: "none",
    arenaId: "void_throne",
    voiceLine: "There is no leaderboard here.",
    introLines: [
      "There is no leaderboard here.",
      "You already lost the moment you started counting wins.",
      "I am what's left when everyone stops pretending.",
    ],
    colors: { primary: "#0a0714", secondary: "#1a0a2e", emissive: "#ffffff" },
    moves: {
      special: { damage: 320, animation: "overmog_special_convergence", meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
    isFinalBoss: true,
    useBossModel: true,
  },
};

// Scoped down to 2 fighters (one per available 3D model — Vanguard and Ely,
// see public/models/) while control/facing/animation get nailed down for
// real, per explicit request: get 2 fully working before duplicating back
// up to the full twelve. The other 10 are still fully defined in CHARACTERS
// above (all still usable in story mode) — re-adding them here is enough to
// bring them back into normal versus-mode selection once ready; alternate
// `modelKey` between "vanguard" and "ely" for visual variety.
export const ROSTER_ORDER = [
  "gautham",
  "garv",
];

// Story-mode-only entries (bosses) live outside ROSTER_ORDER so they never
// show up in the normal versus-mode character/opponent picker.
export const ROSTER = ROSTER_ORDER.map((id) => CHARACTERS[id]);
