import type { CharacterConfig } from "./types";

// The full Mog Off roster (PRD 6.2 / SRD sec 5). Stats, moves, and visual
// params are data-driven so the shared combat resolver and stage builder
// work for all twelve without new code paths. Combat is punch/kick/block/
// jump plus one elemental special per character — per-character feel comes
// from `build` (see BUILD_POWER in lib/combat.ts) plus the special.
export const CHARACTERS: Record<string, CharacterConfig> = {
  gautham: {
    id: "gautham",
    name: "Gautham",
    title: "The Furnace",
    element: "fire",
    bio: "Thinks he's the main character. In the Mogsphere, he might actually be right.",
    health: 1000,
    build: "normal",
    accessory: "spikes",
    arenaId: "fire",
    voiceLine: "Burn with me!",
    introLines: ["Burn with me!", "You picked the wrong ring.", "Watch closely — this is the good part."],
    colors: { primary: "#3a160c", secondary: "#d1401f", emissive: "#ff7a1a" },
    moves: {
      special: { name: "Chain Pull", damage: 220, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: true,
  },
  garv: {
    id: "garv",
    name: "Garv",
    title: "The Stillwater",
    element: "ice",
    bio: "Would rather win with one perfect cut than ten sloppy ones.",
    health: 1000,
    build: "normal",
    accessory: "crystal",
    arenaId: "ice",
    voiceLine: "Everything ends in silence.",
    introLines: ["Everything ends in silence.", "Make it quick, then.", "You'll feel this later. Just not for long."],
    colors: { primary: "#0e2430", secondary: "#1c3a52", emissive: "#7fe3ff" },
    moves: {
      special: { name: "Deep Freeze", damage: 220, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: true,
  },
  anvith: {
    id: "anvith",
    name: "Anvith",
    title: "The Current",
    element: "electric",
    bio: "Meditates between rounds. It works better than it should.",
    health: 1000,
    build: "normal",
    accessory: "beads",
    arenaId: "storm_zen",
    voiceLine: "Feel the current.",
    introLines: ["Feel the current.", "Breathe. This won't take long.", "I already saw how this ends."],
    colors: { primary: "#171029", secondary: "#2b2140", emissive: "#b98bff" },
    moves: {
      special: { name: "Conduit", damage: 200, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ryan: {
    id: "ryan",
    name: "Ryan",
    title: "The Underground",
    element: "kinetic",
    bio: "Doesn't need an element. Just needs one good angle to close the distance.",
    health: 1150,
    build: "bulky",
    accessory: "none",
    arenaId: "concrete_arena",
    voiceLine: "Down you go!",
    introLines: ["Down you go!", "Let's skip the small talk.", "I've done this a hundred times."],
    colors: { primary: "#201c18", secondary: "#4a3226", emissive: "#ffb454" },
    moves: {
      special: { name: "Suplex", damage: 230, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  chandan: {
    id: "chandan",
    name: "Chandan",
    title: "The Afterimage",
    element: "speed",
    bio: "Talks the whole fight. You only notice when the talking stops.",
    health: 850,
    build: "slim",
    accessory: "hood",
    arenaId: "neon_alley",
    voiceLine: "Catch me if you can.",
    introLines: ["Catch me if you can.", "Oh, you're actually trying? Cute.", "Blink and it's over."],
    colors: { primary: "#140a24", secondary: "#241f38", emissive: "#ff4fd8" },
    moves: {
      special: { name: "Afterimage Rush", damage: 200, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  elango: {
    id: "elango",
    name: "Elango",
    title: "The Quarry",
    element: "earth",
    bio: "Slow to anger. The ground gets there first.",
    health: 1300,
    build: "tank",
    accessory: "pauldron",
    arenaId: "stone_quarry",
    voiceLine: "The ground remembers.",
    introLines: ["The ground remembers.", "I've been patient long enough.", "Sit down. This won't take long."],
    colors: { primary: "#2c2416", secondary: "#55442c", emissive: "#b5ff6a" },
    moves: {
      special: { name: "Upheaval", damage: 240, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  dev: {
    id: "dev",
    name: "Dev",
    title: "The Core",
    element: "tech",
    bio: "Brought receipts, a drone, and three backup plans.",
    health: 1000,
    build: "normal",
    accessory: "visor",
    arenaId: "server_core",
    voiceLine: "Running final sequence.",
    introLines: ["Running final sequence.", "I already simulated this. I win.", "Don't take it personally."],
    colors: { primary: "#04171c", secondary: "#1b1f2a", emissive: "#43f5ff" },
    moves: {
      special: { name: "Overclock", damage: 210, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  aadit: {
    id: "aadit",
    name: "Aadit",
    title: "The Mirror",
    element: "shift",
    bio: "Already fought this exact fight in his head. He won that one too.",
    health: 1000,
    build: "normal",
    accessory: "chrome",
    arenaId: "mirror_hall",
    voiceLine: "I've already won this fight.",
    introLines: ["I've already won this fight.", "You'll fight exactly like I expect.", "I'm going to enjoy copying that."],
    colors: { primary: "#1c1c26", secondary: "#2e2e38", emissive: "#d9d9e8" },
    moves: {
      special: { name: "Copycat", damage: 215, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  rishi: {
    id: "rishi",
    name: "Rishi",
    title: "The Silence",
    element: "steel",
    bio: "Says almost nothing. The blade says the rest.",
    health: 850,
    build: "slim",
    accessory: "topknot",
    arenaId: "dojo",
    voiceLine: "One cut is enough.",
    introLines: ["One cut is enough.", "...", "Draw your weapon. I'll wait."],
    colors: { primary: "#18140f", secondary: "#1a1a22", emissive: "#e6e6f0" },
    moves: {
      special: { name: "Iaido", damage: 260, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ronith: {
    id: "ronith",
    name: "Ronith",
    title: "The Gale",
    element: "wind",
    bio: "Never lands where you're looking.",
    health: 850,
    build: "slim",
    accessory: "scarf",
    arenaId: "sky_temple",
    voiceLine: "Try to keep up.",
    introLines: ["Try to keep up.", "You'll need to be faster than that.", "Let's see if you can even touch me."],
    colors: { primary: "#102420", secondary: "#1e3a34", emissive: "#baffe0" },
    moves: {
      special: { name: "Cyclone", damage: 205, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  tej: {
    id: "tej",
    name: "Tej",
    title: "The Strike",
    element: "lightning",
    bio: "Too fast to block, too impatient to combo.",
    health: 1000,
    build: "normal",
    accessory: "shins",
    arenaId: "storm_ring",
    voiceLine: "Too fast, too late.",
    introLines: ["Too fast, too late.", "I'm already bored.", "Try to keep this interesting."],
    colors: { primary: "#1c1c10", secondary: "#2a2340", emissive: "#f5e642" },
    moves: {
      special: { name: "Thunderstep", damage: 215, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  mohammed: {
    id: "mohammed",
    name: "Mohammed",
    title: "The Anchor",
    element: "kinetic",
    bio: "Doesn't flinch. Never has. The fight ends when he decides it does.",
    health: 1150,
    build: "tank",
    accessory: "pauldron",
    arenaId: "concrete_arena",
    voiceLine: "You're not moving me.",
    introLines: ["You're not moving me.", "Take your best shot.", "This is going to take a while."],
    colors: { primary: "#1c2420", secondary: "#3a4a40", emissive: "#3dffb8" },
    moves: {
      special: { name: "Iron Anchor", damage: 235, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  dhanuh: {
    id: "dhanuh",
    name: "Dhanuh",
    title: "The Draft",
    element: "wind",
    bio: "Talks less than the wind does. Says more.",
    health: 850,
    build: "slim",
    accessory: "scarf",
    arenaId: "sky_temple",
    voiceLine: "Feel the draft.",
    introLines: ["Feel the draft.", "You'll lose sight of me.", "Let's move."],
    colors: { primary: "#1a2620", secondary: "#2e4a3a", emissive: "#9dffe0" },
    moves: {
      special: { name: "Tailwind", damage: 200, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  srinath: {
    id: "srinath",
    name: "Srinath",
    title: "The Signal",
    element: "tech",
    bio: "Reads the fight three moves ahead. Still gets hit sometimes.",
    health: 1000,
    build: "normal",
    accessory: "visor",
    arenaId: "server_core",
    voiceLine: "Signal locked.",
    introLines: ["Signal locked.", "Running the numbers.", "This won't take long."],
    colors: { primary: "#0c1a24", secondary: "#1e3a4a", emissive: "#4dd9ff" },
    moves: {
      special: { name: "Uplink", damage: 210, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  vaishnav: {
    id: "vaishnav",
    name: "Vaishnav",
    title: "The Surge",
    element: "lightning",
    bio: "Doesn't wait for an opening. Makes one.",
    health: 1000,
    build: "normal",
    accessory: "shins",
    arenaId: "storm_ring",
    voiceLine: "Here it comes.",
    introLines: ["Here it comes.", "No warning shots.", "Brace yourself."],
    colors: { primary: "#241c10", secondary: "#4a3820", emissive: "#ffd23d" },
    moves: {
      special: { name: "Surge", damage: 215, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ram: {
    id: "ram",
    name: "Ram",
    title: "The Guard",
    element: "steel",
    bio: "Trained for years to make this look effortless. It isn't.",
    health: 1050,
    build: "bulky",
    accessory: "chrome",
    arenaId: "dojo",
    voiceLine: "Stand your ground.",
    introLines: ["Stand your ground.", "I won't ask twice.", "Guard up."],
    colors: { primary: "#1c1c1c", secondary: "#3a3a3e", emissive: "#c9c9d9" },
    moves: {
      special: { name: "Steel Guard", damage: 250, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  abhinav: {
    id: "abhinav",
    name: "Abhinav",
    title: "The Echo",
    element: "shift",
    bio: "By the time you notice him, he's already somewhere else.",
    health: 900,
    build: "slim",
    accessory: "hood",
    arenaId: "mirror_hall",
    voiceLine: "Catch the echo.",
    introLines: ["Catch the echo.", "You're chasing a copy.", "Already gone."],
    colors: { primary: "#1a1424", secondary: "#2e2440", emissive: "#c99bff" },
    moves: {
      special: { name: "Echo Step", damage: 205, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  viraat: {
    id: "viraat",
    name: "Viraat",
    title: "The Architect",
    element: "void",
    bio: "Built the arena. Decides who leaves it.",
    health: 1300,
    build: "tank",
    accessory: "crown",
    arenaId: "void_throne",
    voiceLine: "I built this arena. I decide who leaves it.",
    introLines: ["I built this arena. I decide who leaves it.", "Everyone ends up here eventually.", "Let's see what you've learned."],
    colors: { primary: "#0a0714", secondary: "#0a0a0f", emissive: "#b98bff" },
    moves: {
      special: { name: "Keystone", damage: 280, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
    isStoryBoss: true,
  },
  overmog: {
    id: "overmog",
    name: "Overmog",
    title: "The Unranked",
    element: "prism",
    bio: "Not a thirteenth fighter. What's left in the ring after twelve people spend years trying to out-mog each other in it.",
    health: 1600,
    build: "tank",
    accessory: "none",
    arenaId: "void_throne",
    voiceLine: "There is no leaderboard here.",
    introLines: [
      "There is no leaderboard here.",
      "You already lost the moment you started counting wins.",
      "I am what's left when everyone stops pretending.",
    ],
    colors: { primary: "#0a0714", secondary: "#1a0a2e", emissive: "#ffffff" },
    moves: {
      special: { name: "Convergence", damage: 320, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
    isFinalBoss: true,
    useBossModel: true,
  },
  bhanuh: {
    id: "bhanuh",
    name: "Bhanuh",
    title: "The Ember",
    element: "fire",
    bio: "Shows up late to everything except a fight.",
    health: 850,
    build: "slim",
    accessory: "hood",
    arenaId: "fire",
    voiceLine: "Still warming up.",
    introLines: ["Still warming up.", "You're the practice round.", "Let's make this quick."],
    colors: { primary: "#3a1c10", secondary: "#a8431c", emissive: "#ff9a3d" },
    moves: {
      special: { name: "Ember Wave", damage: 210, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  pratheek: {
    id: "pratheek",
    name: "Pratheek",
    title: "The Circuit",
    element: "electric",
    bio: "Overthinks every single decision except the ones that matter.",
    health: 1000,
    build: "normal",
    accessory: "beads",
    arenaId: "storm_zen",
    voiceLine: "Circuit's live.",
    introLines: ["Circuit's live.", "I've got a plan. You're not in it.", "Don't overthink this. I already did."],
    colors: { primary: "#1a1030", secondary: "#33234a", emissive: "#c9a0ff" },
    moves: {
      special: { name: "Short Circuit", damage: 205, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  diddy: {
    id: "diddy",
    name: "Diddy",
    title: "The Blur",
    element: "speed",
    bio: "Somehow always the loudest one in the room and the hardest one to actually hit.",
    health: 850,
    build: "slim",
    accessory: "scarf",
    arenaId: "neon_alley",
    voiceLine: "Can't catch a blur.",
    introLines: ["Can't catch a blur.", "You blinked. I won.", "Try to keep this interesting."],
    colors: { primary: "#1c0f22", secondary: "#33203c", emissive: "#ff6fe0" },
    moves: {
      special: { name: "Blur Step", damage: 200, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  saishnav: {
    id: "saishnav",
    name: "Vex",
    title: "The Hollow",
    element: "void",
    bio: "Answers every question with another question. Fights the same way.",
    health: 1000,
    build: "normal",
    accessory: "hood",
    arenaId: "void_throne",
    voiceLine: "Nothing to see here.",
    introLines: ["Nothing to see here.", "You're fighting the idea of me.", "Already three steps ahead."],
    colors: { primary: "#0a0714", secondary: "#170f28", emissive: "#9d6bff" },
    moves: {
      special: { name: "Hollow Point", damage: 245, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  vikram: {
    id: "vikram",
    name: "Vikram",
    title: "The Bedrock",
    element: "earth",
    bio: "Immovable in every sense of the word, including scheduling.",
    health: 1300,
    build: "tank",
    accessory: "pauldron",
    arenaId: "stone_quarry",
    voiceLine: "Bedrock doesn't move.",
    introLines: ["Bedrock doesn't move.", "Go ahead. Push.", "You'll tire out before I do."],
    colors: { primary: "#241c10", secondary: "#4a3a20", emissive: "#d4ff6a" },
    moves: {
      special: { name: "Bedrock Slam", damage: 240, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  ishaan: {
    id: "ishaan",
    name: "Ishaan",
    title: "The Frost",
    element: "ice",
    bio: "Colder than Garv and will absolutely tell you that to your face.",
    health: 1000,
    build: "normal",
    accessory: "crystal",
    arenaId: "ice",
    voiceLine: "Feel the frost.",
    introLines: ["Feel the frost.", "This ends cold.", "Garv wishes he hit this hard."],
    colors: { primary: "#0c202c", secondary: "#1c3a4c", emissive: "#6fd9ff" },
    moves: {
      special: { name: "Absolute Zero", damage: 225, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  srinips: {
    id: "srinips",
    name: "Srinips",
    title: "The Loop",
    element: "tech",
    bio: "Has a script for this. Has a script for everything.",
    health: 1000,
    build: "normal",
    accessory: "visor",
    arenaId: "server_core",
    voiceLine: "Looping the sequence.",
    introLines: ["Looping the sequence.", "Same fight, better odds.", "I've run this a hundred times."],
    colors: { primary: "#071c20", secondary: "#123a40", emissive: "#3dffe0" },
    moves: {
      special: { name: "Infinite Loop", damage: 210, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
  modih: {
    id: "modih",
    name: "Modih",
    title: "The Vault",
    element: "steel",
    bio: "Built like he's never lost an argument. Hasn't.",
    health: 1150,
    build: "bulky",
    accessory: "chrome",
    arenaId: "dojo",
    voiceLine: "Vault's shut.",
    introLines: ["Vault's shut.", "Nothing gets through.", "You'll need more than that."],
    colors: { primary: "#16161a", secondary: "#33333c", emissive: "#dcdce8" },
    moves: {
      special: { name: "Vault Break", damage: 250, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  pushkal: {
    id: "pushkal",
    name: "Pushkal",
    title: "The Featherweight",
    element: "kinetic",
    bio: "Takes a hit worse than anyone in the friend group. Makes up for it by hitting first.",
    health: 700,
    build: "slim",
    accessory: "none",
    arenaId: "concrete_arena",
    voiceLine: "One hit's all it takes.",
    introLines: ["One hit's all it takes.", "Don't let me get close.", "I only need one shot."],
    colors: { primary: "#1c1408", secondary: "#3a2c10", emissive: "#ffcf4d" },
    moves: {
      special: { name: "Glass Cannon", damage: 260, meterGain: 0, cinematic: true },
    },
    unlockedByDefault: false,
  },
  cupcake: {
    id: "cupcake",
    name: "The Cupcake",
    title: "The Unexplained",
    element: "wind",
    bio: "Nobody remembers who added it to the roster. Nobody's brave enough to remove it.",
    health: 1150,
    build: "bulky",
    accessory: "none",
    arenaId: "sky_temple",
    voiceLine: "...",
    introLines: ["...", "(sprinkles ominously)", "You weren't ready for this."],
    colors: { primary: "#2c1420", secondary: "#5c2c40", emissive: "#ff8fd0" },
    moves: {
      special: { name: "Sugar Rush", damage: 215, meterGain: 0, projectile: true, cinematic: true },
    },
    unlockedByDefault: false,
  },
};

// Every CHARACTERS entry except Overmog, who isn't a friend at all (see
// lore.ts / overmog's bio: "not a thirteenth fighter"). Viraat is both one
// of the original twelve AND story mode's mid-ladder gatekeeper
// (isStoryBoss) — that only affects where he shows up in the story ladder,
// not whether he's pickable here. Mohammed through Abhinav, and Bhanuh
// through The Cupcake, joined the roster later, sharing an element/arena
// with an existing friend where no spare arena existed for a new theme.
// "Vex" is Saishnav's in-game alias — the CHARACTERS key stays `saishnav`
// (matches the person), only `name` shows the nickname.
export const ROSTER_ORDER = [
  "gautham",
  "garv",
  "anvith",
  "ryan",
  "chandan",
  "elango",
  "dev",
  "aadit",
  "rishi",
  "ronith",
  "tej",
  "viraat",
  "mohammed",
  "dhanuh",
  "srinath",
  "vaishnav",
  "ram",
  "abhinav",
  "bhanuh",
  "pratheek",
  "diddy",
  "saishnav",
  "vikram",
  "ishaan",
  "srinips",
  "modih",
  "pushkal",
  "cupcake",
];

// Overmog lives outside ROSTER_ORDER so it never shows up in the normal
// versus-mode character/opponent picker — final-boss-only, no humanoid
// body to select in the first place (see Fighter2D's boss branch).
export const ROSTER = ROSTER_ORDER.map((id) => CHARACTERS[id]);
